alias ez='v ~/.zshrc' 
alias sz='source ~/.zshrc'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c='cd'
alias v='vim'
alias o='open'
alias l='ls -lah'
alias ls='ls -h'
alias xx='logout'
alias cl='clear'
alias gr='grep --color -rnC 3 .'
alias dev='tmux a -d -t dev'
alias ndev='tmux new-session -s dev'
 
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gb='git branch'
alias gk='git checkout'
alias gd='git diff --name-only'
alias gl="git log -10 --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gca='git commit --amend'
alias gcp='git cherry-pick'
